### ISSUE TITLE
about parse

### ISSUE THREAD

**Issue by BhumeshNick** [tinashec/Rooms#1]
can you please tell me about databse?

**Comment by tinashec** [comment]
Hi BhumeshNick, I do not quite understand your question. But from what I can make of it, the back-end functionality is handled by Parse. Having said that, they are responsible for the database and all other back-end related services. I understand that they use MongoDB, a NoSQL type of database. I hope this helps.

**Comment by BhumeshNick** [comment]
how parse handle back end functionality ? can u please explain

**Comment by tinashec** [comment]
The best place to start of from is here: https://github.com/parse-community/parse-server#getting-started. How exactly this is done, its beyond my knowledge but the Parse server allows for data transfer from your application to the server via API's. You could try posting the question on Stackoverflow. I'm sure there are more knowledgeable people on that platform.

**Comment by BhumeshNick** [comment]
can you tell me how you connect parse with app

**Comment by tinashec** [comment]
Hi, go through this tutorial https://robusttechhouse.com/install-parse-server-use-backend-android-apps/, from there apply the same knowledge by using back4app.com.

**Comment by BhumeshNick** [comment]
how you create database in back4app?
can you please share your database code?

**Comment by BhumeshNick** [comment]
edit and search features not working properly

**Comment by tinashec** [comment]
Edit and search features on which platform? Your app or from Parse back-end
