### ISSUE TITLE
Hi developer Tinashec, I would like to let you know that I used your code of this project and modified the code

### ISSUE THREAD

**Issue by AbheeHub** [tinashec/Rooms#2]
Hi dev. @tinashec I have **used your this project's code** and **modified** to have **some extra functionalities and features**. Kindly have a look at it here: [https://github.com/AbheeHub/Room_Finder](url) 
Thanks
Abhinav

P.S: credit all goes to you for the app base.

**Comment by tinashec** [comment]
Noted Abhinav,

Not an issue, glad to know the code is helping out someone.

Happy coding.

Cheers,
Tinashe
